services:
  web-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "5000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  dataprocessor-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "5100:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  postgres:
    ports:
      - "5432:5432"


  pgadmin:
    ports:
      - "5050:80"


  elasticsearch:
    ports:
      - "9200:9200"


  kibana:
    ports:
      - "5601:5601"


  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"


  seq:
    ports:
      - "5081:80"