// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720083815_Rename-TaskEntities")]
    partial class RenameTaskEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Activities.TodoActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActivityType")
                        .HasColumnType("integer")
                        .HasColumnName("activity_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<Guid>("TodoItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("todo_item_id");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_activities");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_todo_activities_created_at_utc");

                    b.HasIndex("TodoItemId")
                        .HasDatabaseName("ix_todo_activities_todo_item_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_todo_activities_user_id");

                    b.ToTable("todo_activities", "public");
                });

            modelBuilder.Entity("Domain.Permissions.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_description");

                    b.ToTable("permissions", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bbb01f3-adbf-4fed-b5a6-70d3fe07da7d"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "todo:access"
                        },
                        new
                        {
                            Id = new Guid("f7c8b043-d353-4a0a-8745-e0ce95a414ac"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "users:access"
                        },
                        new
                        {
                            Id = new Guid("d5b5de09-34d0-4f34-8d60-410db716454b"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "permission:access"
                        },
                        new
                        {
                            Id = new Guid("1090b64b-1b68-4365-98b4-0e1f64e64f53"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "activity:access"
                        });
                });

            modelBuilder.Entity("Domain.Todos.TodoAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("NOW()");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stored_file_name");

                    b.Property<Guid>("TodoItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("todo_item_id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_todo_attachments");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("ix_todo_attachments_created_on");

                    b.HasIndex("TodoItemId")
                        .HasDatabaseName("ix_todo_attachments_todo_item_id");

                    b.ToTable("todo_attachments", "public");
                });

            modelBuilder.Entity("Domain.Todos.TodoDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DependsOnTodoItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("depends_on_todo_item_id");

                    b.Property<Guid>("TodoItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("todo_item_id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_todo_dependencies");

                    b.HasIndex("DependsOnTodoItemId")
                        .HasDatabaseName("ix_todo_dependencies_depends_on_todo_item_id");

                    b.HasIndex("TodoItemId")
                        .HasDatabaseName("ix_todo_dependencies_todo_item_id");

                    b.ToTable("todo_dependencies", "public");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("categories");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.PrimitiveCollection<string[]>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_items");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_todo_items_user_id");

                    b.ToTable("todo_items", "public");
                });

            modelBuilder.Entity("Domain.Todos.TodoSubItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TodoItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("todo_item_id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_todo_sub_items");

                    b.HasIndex("TodoItemId")
                        .HasDatabaseName("ix_todo_sub_items_todo_item_id");

                    b.ToTable("todo_sub_items", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d49c37cb-4774-4399-9848-63f89710491f"),
                            CreatedOn = new DateTime(2026, 7, 16, 13, 25, 57, 0, DateTimeKind.Utc),
                            Email = "james.bond@mail.com",
                            FirstName = "james",
                            LastName = "bond",
                            PasswordHash = "646584747216FCD2E04A09CB831A495213422447104F0DAE7103ACAAB05AD988-3DF7AD47EDD6E4B714EA6898AF9A6B68"
                        });
                });

            modelBuilder.Entity("Domain.Users.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_user_permissions_permission_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_permissions_user_id");

                    b.ToTable("user_permissions", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019f6b1a-f9a3-7ff2-bb54-9223cdf5d34f"),
                            CreatedOn = new DateTime(2026, 7, 16, 13, 25, 57, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("d5b5de09-34d0-4f34-8d60-410db716454b"),
                            UserId = new Guid("d49c37cb-4774-4399-9848-63f89710491f")
                        },
                        new
                        {
                            Id = new Guid("019f6b1c-a541-7310-a652-021d00ca5fe8"),
                            CreatedOn = new DateTime(2026, 7, 16, 13, 27, 47, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("5bbb01f3-adbf-4fed-b5a6-70d3fe07da7d"),
                            UserId = new Guid("d49c37cb-4774-4399-9848-63f89710491f")
                        },
                        new
                        {
                            Id = new Guid("019f6b1d-6e35-71e4-a136-37cd0f95ad0d"),
                            CreatedOn = new DateTime(2026, 7, 16, 13, 28, 38, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("1090b64b-1b68-4365-98b4-0e1f64e64f53"),
                            UserId = new Guid("d49c37cb-4774-4399-9848-63f89710491f")
                        },
                        new
                        {
                            Id = new Guid("019f6b1d-db36-7d5a-ba4b-9be1aca1137b"),
                            CreatedOn = new DateTime(2026, 7, 16, 13, 29, 6, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("f7c8b043-d353-4a0a-8745-e0ce95a414ac"),
                            UserId = new Guid("d49c37cb-4774-4399-9848-63f89710491f")
                        });
                });

            modelBuilder.Entity("Domain.Activities.TodoActivity", b =>
                {
                    b.HasOne("Domain.Todos.TodoItem", "TodoItem")
                        .WithMany("TaskActivities")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_activities_todo_items_todo_item_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_activities_users_user_id");

                    b.Navigation("TodoItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Todos.TodoAttachment", b =>
                {
                    b.HasOne("Domain.Todos.TodoItem", "TodoItem")
                        .WithMany("Attachments")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_attachments_todo_items_todo_item_id");

                    b.Navigation("TodoItem");
                });

            modelBuilder.Entity("Domain.Todos.TodoDependency", b =>
                {
                    b.HasOne("Domain.Todos.TodoItem", "DependsOnTodoItem")
                        .WithMany()
                        .HasForeignKey("DependsOnTodoItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_todo_dependencies_todo_items_depends_on_todo_item_id");

                    b.HasOne("Domain.Todos.TodoItem", "TodoItem")
                        .WithMany("Dependencies")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_dependencies_todo_items_todo_item_id");

                    b.Navigation("DependsOnTodoItem");

                    b.Navigation("TodoItem");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_items_users_user_id");
                });

            modelBuilder.Entity("Domain.Todos.TodoSubItem", b =>
                {
                    b.HasOne("Domain.Todos.TodoItem", "TodoItem")
                        .WithMany("SubItems")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_sub_items_todo_items_todo_item_id");

                    b.Navigation("TodoItem");
                });

            modelBuilder.Entity("Domain.Users.UserPermission", b =>
                {
                    b.HasOne("Domain.Permissions.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_permissions_permission_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_users_user_id");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Dependencies");

                    b.Navigation("SubItems");

                    b.Navigation("TaskActivities");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
