<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Todos\Activities\ITaskActivityService.cs" />
    <Compile Remove="Todos\Activities\ITodoActivityService.cs" />
    <Compile Remove="Todos\Activities\TaskActivityService.cs" />
    <Compile Remove="Todos\Activities\TodoActivityLogRequestedDomainEventHandler.cs" />
    <Compile Remove="Todos\Activities\TodoActivityService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="OpenAI" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="System.Linq.Dynamic.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="Application.UnitTests" />
  </ItemGroup>

</Project>
