// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Application.Abstractions.Behaviors.LoggingDecorator.CommandHandler`2.Handle(`0,System.Threading.CancellationToken)~System.Threading.Tasks.Task{SharedKernel.Result{`1}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Application.Abstractions.Behaviors.LoggingDecorator.CommandBaseHandler`1.Handle(`0,System.Threading.CancellationToken)~System.Threading.Tasks.Task{SharedKernel.Result}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Application.Abstractions.Behaviors.LoggingDecorator.QueryHandler`2.Handle(`0,System.Threading.CancellationToken)~System.Threading.Tasks.Task{SharedKernel.Result{`1}}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Application.RabbitMq.Configuration.RabbitMqHostedService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Application.RabbitMq.Configuration.RabbitMqHostedService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Pending>", Scope = "member", Target = "~M:Application.RabbitMq.Configuration.RabbitMqHostedService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Application.Elastic.ElasticTodoSearchService.RebuildTodoIndexAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Application.Elastic.Services.ElasticTodoSearchService.RebuildTodoIndexAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Pending>", Scope = "member", Target = "~M:Application.RabbitMq.RabbitMqHostedService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:Application.RabbitMq.RabbitMqHostedService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Application.RabbitMq.RabbitMqHostedService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Application.Elastic.Services.ElasticTodoSearchService.SearchTodosAsync(System.Guid,Application.Todos.Get.TodoFilter,Domain.API.Sorted,Domain.API.Paginated,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.List{Application.Elastic.Documents.TodoDocument}}")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Application.Elastic.Services.ElasticTodoSearchService.SearchTodosAsync(System.Guid,Application.Todos.Get.TodoFilter,Domain.API.Sorted,Domain.API.Paginated,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Domain.API.PagedResponse{Application.Elastic.Documents.TodoDocument}}")]
